name: publish

on:
  push:
    branches:
      - master

jobs:
  package:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [ 17 ]

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.version }}
          cache: gradle
          distribution: zulu

      - name: publish
        if: ${{ github.ref_name == 'master' }}
        run: |
          scope=minor
          case "${{ github.event.commits[0].message }}" in
            *MAJOR* | *BREAKING*)
              scope=major
              ;;
            *PATCH* | *HOTFIX*)
              scope=patch
              ;;
          esac
          ./gradlew publish reckonTagPush --no-daemon -Preckon.stage=final -Preckon.scope=$scope
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docs:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: use java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          cache: gradle
          distribution: zulu

      - name: docs
        run: ./gradlew javadoc --no-daemon

      - name: pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./build/docs/javadoc
          github_token: ${{ secrets.GITHUB_TOKEN }}
