name: publish

on:
  push:
    tags:
      - "[0-9].[0-9].[0-9]*"

jobs:
  package:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [ 17 ]

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.version }}
          cache: gradle
          distribution: zulu

      - name: publish
        run: ./gradlew publish --no-daemon -Pversion=$(echo ${{ github.ref }} | sed s#refs/tags/##)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docs:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: use java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          cache: gradle
          distribution: zulu

      - name: docs
        run: ./gradlew javadoc --no-daemon -Pversion=$(echo ${{ github.ref }} | sed s#refs/tags/##)

      - name: pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./build/docs/javadoc
          github_token: ${{ secrets.GITHUB_TOKEN }}
