name: publish

on:
  push:
    branches:
      - master
      - major
      - minor
      - hotfix

jobs:
  package:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [ 17 ]

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.version }}
          cache: gradle
          distribution: zulu

      - name: publish snapshot
        if: ${{ github.ref_name == 'master' }}
        run: ./gradlew publish --no-daemon -Preckon.stage=snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: publish release
        if: ${{ github.ref_name != 'master' }}
        run: ./gradlew publish reckonTagPush --no-daemon -Preckon.stage=final -Preckon.scope=${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: sync
        if: ${{ github.ref_name != 'master' }}
        run: |
          git fetch --unshallow
          git checkout master
          git pull
          git merge --no-ff ${{ github.ref_name }} -m "Sync release"

  docs:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: use java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          cache: gradle
          distribution: zulu

      - name: docs
        run: ./gradlew javadoc --no-daemon

      - name: pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./build/docs/javadoc
          github_token: ${{ secrets.GITHUB_TOKEN }}
